### ISSUE TITLE
Do the simulated robots work in ROS 2 and Gazebo 8 (Harmonic)

### ISSUE THREAD

**Issue by Mechazo11** [husky/husky_manipulation#33]
Dear clearpath robotics,

Thank you very much for publicly releasing the robot models and simulation packages for Gazebo.  I was wondering if the simulation packages have been tested with ROS 2 Humble and Gazebo 8 (Harmonic) as I could not confirm that they do from the repository.

With best regards,
@Mechazo11

**Comment by tonybaltovski** [comment]
Please see https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/overview
