### ISSUE TITLE
Husky with UR5 arm gets tilted when the husky is rotated or moved foreward.

### ISSUE THREAD

**Issue by paulsebastian97** [husky/husky_manipulation#4]
When I try to rotate or move the husky with UR5, it gets tilted as shown in the image below. What could be the reason? I have tried reducing the mass of the UR5 arm but that doesn't help.
![tilted husky](https://user-images.githubusercontent.com/44846728/66331328-e7134a00-e94f-11e9-9e9c-84ff45a0ead8.png)

**Comment by dniewinski** [comment]
Sorry for the delay.  There are known issues with the UR + Husky packages in Gazebo.  These packages were created for physical installations. 

If you end up fixing the issue, feel free to make a PR to add Gazebo support
