### ISSUE TITLE
Husky_manipulation UR5/ CB3.X ??

### ISSUE THREAD

**Issue by Abduoit** [husky/husky_manipulation#6]
Hello 
I am trying to use `husky_manipulation` with UR5/ CB3, but I found that this package only supports [ur_modern_driver](https://github.com/ros-industrial/ur_modern_driver) which is officially deprecated and doesn't support CB3 serious. 

Is there husky_manipulation package ?? for UR5 CB3 with [new_ur_driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver)

**Comment by dniewinski** [comment]
This repo currently only supports the ur_modern_driver, which supports CB3 up to 3.91. If you controller is newer than that, you could downgrade without an issue.  This repo should work for the description and the moveit config, just not the driver.  If you make the relevant additions, we would love a PR

**Comment by Abduoit** [comment]
The UR5 version that I currently have is 3.10 and I can't downgrade because I need to use it with RobotiQ gripper which supports at lease CB3/3.10.
I don't know how do I go about that ?

**Comment by dniewinski** [comment]
You could download an earlier version of the software from URs website and roll-back to an earlier version.  As far as the Robotiq, you could connect that to your computer and use the ROS driver to control it, instead of using the UR controller.  

You could also use the official UR ROS driver with 3.10.  I haven't used it yet so I wouldn't be much help

**Comment by Abduoit** [comment]
I tested the official UR ROS driver with 3.10 and it works fine. But I have not used it with husky_manipulation package. 

as you said, another option could work too, where I connect the RobotiQ directly to the P.C. and use this husky_manipulation repo with UR < 3.10.

**Comment by Abduoit** [comment]
Hi @dniewinski 

I was going to downgrade the URcap from 3.10 to 3.9 in order to use this repo, I need husky_manipulation with moviet and driver. 

I tried to bring up the husky_ur5 as shown below but I got the following error, I also tried to change the `HUSKY_UR_IP 192.168.131.40` to `HUSKY_UR_IP 192.168.131.1` but same error. I am just wondering if this normal for now and it will not appear when I use URcap 3.9. Since I feel I shouldn't get Connection Failed?!

```
administrator@administrator:~/catkin_ws$ roslaunch husky_ur_bringup husky_ur_bringup.launch
... logging to /home/administrator/.ros/log/715c89c6-fdc5-11ea-9980-003018cfc22a/roslaunch-administrator-9684.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.42.0.241:39265/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /tf2_buffer_server/buffer_size: 120.0
 * /ur_driver/prefix: ur_arm_
 * /ur_driver/robot_ip_address: 192.168.131.1
 * /ur_driver/servoj_time: 0.008

NODES
  /
    tf2_buffer_server (tf2_ros/buffer_server)
    ur_driver (ur_modern_driver/ur_driver)

ROS_MASTER_URI=http://localhost:11311

process[ur_driver-1]: started with pid [9714]
process[tf2_buffer_server-2]: started with pid [9715]
[ INFO] [1600884549.775702478]: Setting up connection: 192.168.131.1:30003
[ERROR] [1600884549.775776831]: Connection setup failed for 192.168.131.1:30003
[ INFO] [1600884549.775790666]: Setting up connection: 192.168.131.1:30001
[ERROR] [1600884549.775815085]: Connection setup failed for 192.168.131.1:30001
[ WARN] [1600884549.775827190]: Failed to read from stream, reconnecting in 1 seconds...
[ INFO] [1600884550.775943306]: Setting up connection: 192.168.131.1:30001
```



```
administrator@administrator:~/catkin_ws$ hostname -I
192.168.131.1 10.42.0.241
```

**Comment by dniewinski** [comment]
I am actually currently working in the switch to the newer UR driver, but it's coming slowly.

To run the older driver with your robot, you need to set that environment variable to the IP that your UR arm is using.  Common practice is to set the arm to have an IP of 131.40
