### ISSUE TITLE
ERROR: cannot launch node of type [ur_modern_driver/ur_driver]: ur_modern_driver

### ISSUE THREAD

**Issue by mahaidong** [husky/husky_manipulation#8]
i use the driver from  

ros-industrial /universal_robot   https://github.com/ros-industrial/universal_robot

and 

i also check the ur_modern_driver , it said "ur_modern_driver - Deprecated"  https://github.com/ros-industrial/ur_modern_driver

**Comment by dniewinski** [comment]
Yes, the ur_modern driver has been deprecated, and this package hasn't been updated yet.  You can build it from source from the forks on my github page
